import 'dart:async';
import 'package:camera/camera.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:image/image.dart' as img;
import '../../data/models/dataset_item.dart';
import '../../data/models/recognition_result.dart';
import '../../core/constants/app_constants.dart';
import '../../core/utils/image_utils.dart';
import 'ml_service.dart';
import 'ocr_service.dart';

/// Service for real-time recognition from camera frames
/// Implements ROI-based processing with frame aggregation for stability
class RecognitionService {
  final MLService _mlService;
  final OcrService _ocrService;
  
  bool _isProcessing = false;
  final Map<String, AggregatedResult> _aggregatedResults = {};
  
  RecognitionService({
    required MLService mlService,
    required OcrService ocrService,
  })  : _mlService = mlService,
        _ocrService = ocrService;

  /// Process a camera frame and return recognition results
  /// 
  /// MANDATORY ENFORCEMENT: ROI-BASED PROCESSING ONLY
  /// Full-frame inference is STRICTLY FORBIDDEN.
  /// All ML inference must operate ONLY on ROIs generated by RoiGenerator.
  /// If no ROIs are generated, skip ML inference for that frame.
  Future<List<RecognitionResult>> processFrame({
    required CameraImage cameraImage,
    required List<DatasetItem> dataset,
  }) async {
    // ENFORCEMENT: Hard frame-processing lock - drop frame if still processing
    // This implements the mandatory 5 FPS control with aggressive frame dropping
    if (_isProcessing) {
      return []; // Drop frame - never queue
    }

    if (dataset.isEmpty) {
      return [];
    }

    _isProcessing = true;

    try {
      final preprocessedRois = await ImageUtils.processCameraFrameFullPipeline(
        cameraImage,
        modelWidth: AppConstants.modelInputWidth,
        modelHeight: AppConstants.modelInputHeight,
      );

      if (preprocessedRois == null || preprocessedRois.isEmpty) {
        return [];
      }

      final results = await _processPreprocessedRois(preprocessedRois, dataset);
      _updateAggregatedResults(results);
      return _getStableResults();
    } catch (e) {
      debugPrint('Error processing frame: $e');
      return [];
    } finally {
      _isProcessing = false;
    }
  }

  /// Process frame using Preprocessed ROIs from the background pipeline
  /// 
  /// ENFORCEMENT: This is the ONLY allowed inference method.
  Future<List<RecognitionResult>> _processPreprocessedRois(
    List<PreprocessedRoi> rois,
    List<DatasetItem> dataset,
  ) async {
    final results = <RecognitionResult>[];

    for (final roi in rois) {
      // MANDATORY: Extract embedding directly from the pre-normalized Float32List
      final embedding = await _mlService.extractEmbeddingFromFloatData(roi.pixels);
      if (embedding == null) continue;

      // Match against dataset (uses cached embeddings)
      final matches = _matchEmbedding(embedding, dataset);
      
      // Add bounding box to results using the Normalized Rect
      for (final match in matches) {
        results.add(match.copyWith(
          boundingBox: roi.normalizedRect, // normalized (0.0 to 1.0) Rect
        ));
      }
    }

    return results;
  }

  /// Match embedding against dataset
  /// 
  /// EMBEDDING CACHE ENFORCEMENT:
  /// Dataset item embeddings are PRECOMPUTED at import time and stored in Hive.
  /// This method NEVER recomputes dataset embeddings - it only uses cached values.
  /// Query embedding (from camera frame ROI) is computed fresh each time.
  List<RecognitionResult> _matchEmbedding(
    List<double> queryEmbedding,
    List<DatasetItem> dataset,
  ) {
    final results = <RecognitionResult>[];

    // EMBEDDING CACHE ENFORCEMENT:
    // item.embedding is ALWAYS from cache (computed at import time)
    // queryEmbedding is the ONLY fresh computation (from current frame ROI)
    for (final item in dataset) {
      final similarity = _mlService.calculateSimilarity(
        queryEmbedding,
        item.embedding, // CACHED - never recomputed
      );

      // Check if similarity meets threshold
      if (similarity >= AppConstants.similarityThreshold) {
        results.add(RecognitionResult(
          matchedItem: item,
          confidence: similarity,
        ));
      }
    }

    // Sort by confidence (highest first)
    results.sort((a, b) => b.confidence.compareTo(a.confidence));

    // Return top matches
    return results.take(AppConstants.maxMatchResults).toList();
  }

  /// Update aggregated results for temporal stability
  /// 
  /// ENFORCEMENT: Results persist for multiple frames to reduce flicker.
  /// Items are removed only after not being seen for 5 consecutive frames.
  void _updateAggregatedResults(List<RecognitionResult> newResults) {
    final currentItemIds = newResults.map((r) => r.matchedItem.id).toSet();
    
    // Add new observations
    for (final result in newResults) {
      final itemId = result.matchedItem.id;
      
      if (_aggregatedResults.containsKey(itemId)) {
        _aggregatedResults[itemId] = _aggregatedResults[itemId]!.addObservation(
          result.confidence,
          result.boundingBox,
          AppConstants.resultAggregationFrames,
        );
      } else {
        _aggregatedResults[itemId] = AggregatedResult(
          item: result.matchedItem,
          confidenceHistory: [result.confidence],
          boundingBoxHistory: [result.boundingBox],
        );
      }
    }

    // Decay confidence for items not seen in current frame
    final keysToRemove = <String>[];
    
    for (final entry in _aggregatedResults.entries) {
      if (!currentItemIds.contains(entry.key)) {
        // Item not seen in current frame
        // Add a 0.0 confidence observation to organically decay the average
        _aggregatedResults[entry.key] = entry.value.addObservation(
          0.0,
          entry.value.latestBoundingBox, // Keep last known position
          AppConstants.resultAggregationFrames,
        );

        // Mark for removal if confidence drops sufficiently
        if (_aggregatedResults[entry.key]!.averageConfidence < AppConstants.similarityThreshold - 0.05) {
          keysToRemove.add(entry.key);
        }
      }
    }
    
    for (final key in keysToRemove) {
      _aggregatedResults.remove(key);
    }
  }

  /// Get stable results from aggregated data
  List<RecognitionResult> _getStableResults() {
    final results = <RecognitionResult>[];

    for (final aggregated in _aggregatedResults.values) {
      // Only include if average confidence meets threshold
      if (aggregated.averageConfidence >= AppConstants.similarityThreshold) {
        results.add(RecognitionResult(
          matchedItem: aggregated.item,
          confidence: aggregated.averageConfidence,
          boundingBox: aggregated.latestBoundingBox,
        ));
      }
    }

    // Sort by confidence
    results.sort((a, b) => b.confidence.compareTo(a.confidence));

    return results.take(AppConstants.maxMatchResults).toList();
  }

  /// Process a single image (for testing/validation)
  Future<List<RecognitionResult>> recognizeImage({
    required img.Image image,
    required List<DatasetItem> dataset,
  }) async {
    final embedding = await _mlService.extractEmbedding(image);
    if (embedding == null) return [];

    return _matchEmbedding(embedding, dataset);
  }

  /// Boost recognition with OCR (when image similarity is near threshold)
  Future<List<RecognitionResult>> recognizeWithOcr({
    required img.Image image,
    required List<DatasetItem> dataset,
    String? detectedText,
  }) async {
    // Get image-based results
    final imageResults = await recognizeImage(image: image, dataset: dataset);

    if (!_ocrService.isInitialized || detectedText == null) {
      return imageResults;
    }

    // Boost scores with OCR for near-threshold matches
    final boostedResults = <RecognitionResult>[];

    for (final result in imageResults) {
      double finalConfidence = result.confidence;

      // If item has OCR text and confidence is near threshold
      if (result.matchedItem.ocrText != null &&
          result.confidence > AppConstants.similarityThreshold - 0.1) {
        final textSimilarity = _ocrService.calculateTextSimilarity(
          detectedText,
          result.matchedItem.ocrText!,
        );

        finalConfidence = _ocrService.combineScores(
          imageSimilarity: result.confidence,
          textSimilarity: textSimilarity,
          threshold: AppConstants.similarityThreshold,
        );
      }

      boostedResults.add(result.copyWith(
        confidence: finalConfidence,
        detectedText: detectedText,
      ));
    }

    // Re-sort and filter
    boostedResults.sort((a, b) => b.confidence.compareTo(a.confidence));
    return boostedResults
        .where((r) => r.confidence >= AppConstants.similarityThreshold)
        .take(AppConstants.maxMatchResults)
        .toList();
  }

  /// Reset aggregation (call when switching modes or clearing)
  void resetAggregation() {
    _aggregatedResults.clear();
  }

  /// Check if currently processing
  bool get isProcessing => _isProcessing;
}
